name-template: 'ğŸš€ v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸ’¡ Features'
    labels:
      - 'âœ… CheckList'
      - 'ğŸŒˆ Feature'
  - title: 'ğŸ› Bug fixes'
    labels:
      - 'âš ï¸ Bug'
  - title: 'ğŸ¤¯ Inner Changes'
    labels:
      - 'ğŸ“¦ Chore'
      - 'ğŸ“ƒ Docs'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'âšªï¸ Release major'
  minor:
    labels:
      - 'ğŸŸ  Release minor'
  patch:
    labels:
      - 'ğŸŸ¡ Release patch'
  default: minor
template: |
  ## ğŸš€ ì´ë²ˆ ë²„ì „ì—ì„œëŠ” ì–´ë–¤ ì ë“¤ì´ ë³€ê²½ë˜ì—ˆëŠ”ì§€ í™•ì¸í•´ë³¼ê¹Œìš”?
  ---
  $CHANGES
no-changes-template: 'ì•—! ë³€ê²½ì‚¬í•­ì´ ì—†ì–´ìš”. ğŸ˜–'
